apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-backup-pv
  labels:
    disk: pg-backup-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: NFS_PATH_PLACEHOLDER
    server: NFS_IP_ADDRESS_PLACEHOLDER
